language: node_js
node_js:
    - '10'
# Only build for merge into develop or master
branches:
  only:
  - master
  - develop
# Install dependencies
install:
  - npm install
# Test and build
script:
  - ng lint
  - npm run test
  - npm run electron:windows
  - npm run electron:linux
# Only runs on master update
# Version bump, generate changelog
before_deploy:
  - semantic-release
# Create a release on GitHub
deploy:
  provider: releases
  edge: true
  file:
    - release/*.exe
    - release/*.AppImage
  on:
    branch: master
