language: node_js
node_js:
    - '10'
# Install dependencies
install:
  - npm install
# Test and build
script:
  - ng lint
  - npm run test
  - npm run build
# Only runs on master update
# Version bump, generate changelog
before_deploy:
  - semantic-release
# Create a release on GitHub
deploy:
  provider: releases
  edge: true
  file:
    - release/*.exe
    - release/*.AppImage
  on:
    branch: master
