# We want to trigger on PR to develop, but need to trigger on push to master so deploy steps are run
if: (type = pull_request AND branch = develop) OR (type = push AND branch = master)

# Config
language: node_js
os: windows
node_js:
    - '10'

# Start of pipeline
# Install dependencies
install:
  - npm install
# Test and build
script:
  - ng lint
  - npm run test
  - npm run electron:windows
  - npm run electron:linux
# Only runs on master update
# Version bump, generate changelog
before_deploy:
  - semantic-release
# Create a release on GitHub
deploy:
  provider: releases
  edge: true
  file:
    - release/*.exe
    - release/*.AppImage
  on:
    branch: master
